CREATE  TABLE IF NOT EXISTS WARSHIPS (
  ID INTEGER  PRIMARY KEY AUTOINCREMENT ,
  DataCreate DATE not NULL DEFAULT  CURRENT_TIMESTAMP,
  Schet INTEGER NOT NULL DEFAULT 50,
  NamePlayer TEXT NOT NULL DEFAULT '-'
);